name: Python Install and Tests

on:
  push:
    paths:
      - 'src/**'
      - 'tests/**'
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: Install just the lint dependencies first
      run: python -m pip install flake8 isort ruff
    - name: Lint with ruff
      run: ruff check
    - name: Check format with ruff
      run: ruff format --check

    - name: Install dependencies
      run: |
        sudo apt install libimage-exiftool-perl -y
        python -m pip install --upgrade pip
        python -m pip install .[lint,test,pipeline]

    - name: Test with pytest
      run: pytest --cov-report xml:coverage.xml
    - uses: actions/upload-artifact@v4
      with:
        name: coverage.xml
        path: coverage.xml